name: Deploy on GitHub Pages
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: atirut-w/mkdocs-deploy@master
        with:
          extra-packages: mkdocs-material pymdown-extensions mkdocs-git-revision-date-localized-plugin
